services:
  speaker:
    build: .
    container_name: discord_spot_speaker
    expose:
      - "3000"
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - speaker-network

  caddy:
    image: caddy:2.11.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - speaker-network
    env_file:
      - ./.env
volumes:
  caddy_data:
  caddy_config:

networks:
  speaker-network:
    driver: bridge
