# Docker compose spawns 4 (2 main) instances: The docker image & reverse proxy for the OAuth web server. Then certbot for https:// (not necessary but it's a good touch) and a reloader for the new certs
services:
  speaker:
    build: .
    container_name: discord_spot_speaker
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - speaker-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - speaker
    restart: unless-stopped
    networks:
      - speaker-network

  # todo: Replace nginx for caddy which has letsencrypt built in...
  #using certbot for lightweight https:// support  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # having this renew to prevent maintanence demand
    entrypoint: >
      sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

  #nginx resetter because aws linux 2023 doesn't have cron :|
  nginx-reloader:
    image: docker:cli
    container_name: nginx-reloader
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: >
      sh -c 'trap exit TERM;
      while :; do
        sleep 12h & wait $${!};
        docker kill --signal=HUP nginx;
      done;'
    restart: unless-stopped

networks:
  speaker-network:
    driver: bridge
